import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ur' | 'es' | 'fr' | 'zh' | 'ar' | 'de' | 'ru' | 'pt' | 'ja' | 'ko' | 'it' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'ltr' | 'rtl';
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    welcome: "Welcome back",
    home: "Home",
    matches: "Matches",
    call: "Call",
    profile: "Profile",
    logout: "Logout",
    signIn: "Sign In",
    getStarted: "Get Started for Free",
    heroTitle: "Master new skills through real human connection.",
    heroSub: "Swap your expertise for knowledge. Teach what you know, learn what you don't.",
    email: "Email address",
    phone: "Phone Number",
    password: "Password",
    continueGoogle: "Continue with Google",
    continueFacebook: "Continue with Facebook",
    or: "Or continue with",
    pendingRequests: "You have 3 pending match requests.",
    hoursExchanged: "Hours Exchanged",
    avgRating: "Average Rating",
    newSkills: "New Skills",
    aiAssistant: "AI Learning Assistant",
    generateRoadmap: "Generate Roadmap",
    recentActivity: "Recent Activity",
    quickActions: "Quick Actions",
    scheduleCall: "Schedule a Call",
    updateSkills: "Update Skills",
    recommendedMatches: "Recommended Matches",
    searchPlaceholder: "Search by name or skill...",
    callNow: "Call Now",
    offers: "Offers",
    wants: "Wants",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    suggestedPath: "Suggested path for",
    clear: "Clear",
    noMatches: "No users found matching your criteria.",
    aiSuggestion: "AI Suggestion",
    skillsExpertise: "Skills & Expertise",
    iCanTeach: "I Can Teach / Offer",
    iWantToLearn: "I Want To Learn",
    noSkillsYet: "No skills added yet.",
    addNewSkill: "Add New Skill",
    skillName: "Skill Name",
    skillType: "Type",
    canTeachOption: "I can teach this",
    wantLearnOption: "I want to learn this",
    addSkillButton: "Add Skill",
    cameraOff: "Camera Off",
    calling: "Calling",
    displayName: "Display Name / Freelance Name",
    location: "Location",
    bio: "Bio",
    sessionWith: "Session with",
    yesterday: "Yesterday",
    mins: "mins",
    createAccount: "Create Account",
    signInAction: "Sign In",
    createNewAccount: "create a new account",
    signInExisting: "sign in to existing account",
    backToHome: "Back to Home",
    demoMode: "Demo Mode. Add real keys in AuthPage.tsx for production."
  },
  hi: {
    welcome: "वापसी पर स्वागत है",
    home: "होम",
    matches: "मैच",
    call: "कॉल",
    profile: "प्रोफाइल",
    logout: "लॉग आउट",
    signIn: "साइन इन करें",
    getStarted: "मुफ्त में शुरू करें",
    heroTitle: "वास्तविक मानवीय संपर्क के माध्यम से नए कौशल में महारत हासिल करें।",
    heroSub: "ज्ञान के लिए अपनी विशेषज्ञता का आदान-प्रदान करें। जो आप जानते हैं उसे सिखाएं, जो आप नहीं जानते उसे सीखें।",
    email: "ईमेल पता",
    phone: "फ़ोन नंबर",
    password: "पासवर्ड",
    continueGoogle: "Google के साथ जारी रखें",
    continueFacebook: "Facebook के साथ जारी रखें",
    or: "या इसके साथ जारी रखें",
    pendingRequests: "आपके पास 3 लंबित मैच अनुरोध हैं।",
    hoursExchanged: "घंटों का आदान-प्रदान",
    avgRating: "औसत रेटिंग",
    newSkills: "नए कौशल",
    aiAssistant: "AI शिक्षण सहायक",
    generateRoadmap: "रोडमैप बनाएं",
    recentActivity: "हाल की गतिविधि",
    quickActions: "त्वरित कार्रवाई",
    scheduleCall: "कॉल शेड्यूल करें",
    updateSkills: "कौशल अपडेट करें",
    recommendedMatches: "अनुशंसित मैच",
    searchPlaceholder: "नाम या कौशल से खोजें...",
    callNow: "अभी कॉल करें",
    offers: "प्रदान करता है",
    wants: "चाहता है",
    editProfile: "प्रोफ़ाइल संपादित करें",
    saveChanges: "बदलाव सहेजें",
    cancel: "रद्द करें",
    suggestedPath: "सुझाया गया रास्ता:",
    clear: "साफ़ करें",
    noMatches: "आपके मानदंडों से मेल खाने वाले कोई उपयोगकर्ता नहीं मिले।",
    aiSuggestion: "AI सुझाव",
    skillsExpertise: "कौशल और विशेषज्ञता",
    iCanTeach: "मैं सिखा सकता हूँ / ऑफ़र",
    iWantToLearn: "मैं सीखना चाहता हूँ",
    noSkillsYet: "अभी तक कोई कौशल नहीं जोड़ा गया।",
    addNewSkill: "नया कौशल जोड़ें",
    skillName: "कौशल का नाम",
    skillType: "प्रकार",
    canTeachOption: "मैं यह सिखा सकता हूँ",
    wantLearnOption: "मैं यह सीखना चाहता हूँ",
    addSkillButton: "कौशल जोड़ें",
    cameraOff: "कैमरा बंद",
    calling: "कॉल किया जा रहा है",
    displayName: "प्रदर्शन नाम",
    location: "स्थान",
    bio: "बायो",
    sessionWith: "सत्र साथ में",
    yesterday: "कल",
    mins: "मिनट",
    createAccount: "खाता बनाएं",
    signInAction: "साइन इन",
    createNewAccount: "नया खाता बनाएं",
    signInExisting: "मौजूदा खाते में साइन इन करें",
    backToHome: "होम पर वापस",
    demoMode: "डेमो मोड।"
  },
  ur: {
    welcome: "خوش آمدید",
    home: "ہوم",
    matches: "میچز",
    call: "کال",
    profile: "پروفائل",
    logout: "لاگ آوٹ",
    signIn: "سائن ان کریں",
    getStarted: "مفت شروعات کریں",
    heroTitle: "حقیقی انسانی رابطے کے ذریعے نئی مہارتیں سیکھیں۔",
    heroSub: "علم کے لیے اپنی مہارت کا تبادلہ کریں۔ جو آپ جانتے ہیں وہ سکھائیں، جو نہیں جانتے وہ سیکھیں۔",
    email: "ای میل پتہ",
    phone: "فون نمبر",
    password: "پاس ورڈ",
    continueGoogle: "Google کے ساتھ جاری رکھیں",
    continueFacebook: "Facebook کے ساتھ جاری رکھیں",
    or: "یا اس کے ساتھ جاری رکھیں",
    pendingRequests: "آپ کی 3 میچ کی درخواستیں زیر التواء ہیں۔",
    hoursExchanged: "تبادلہ شدہ گھنٹے",
    avgRating: "اوسط درجہ بندی",
    newSkills: "نئی مہارتیں",
    aiAssistant: "AI لرننگ اسسٹنٹ",
    generateRoadmap: "روڈ میپ بنائیں",
    recentActivity: "حالیہ سرگرمی",
    quickActions: "فوری اقدامات",
    scheduleCall: "کال کا وقت طے کریں",
    updateSkills: "مہارتیں اپ ڈیٹ کریں",
    recommendedMatches: "تجویز کردہ میچز",
    searchPlaceholder: "نام یا مہارت سے تلاش کریں...",
    callNow: "ابھی کال کریں",
    offers: "پیشکش",
    wants: "چاہتا ہے",
    editProfile: "پروفائل میں ترمیم کریں",
    saveChanges: "تبدیلیاں محفوظ کریں",
    cancel: "منسوخ کریں",
    suggestedPath: "تجویز کردہ راستہ برائے",
    clear: "صاف کریں",
    noMatches: "آپ کے معیار کے مطابق کوئی صارف نہیں ملا۔",
    aiSuggestion: "AI تجویز",
    skillsExpertise: "مہارت اور مہارتیں",
    iCanTeach: "میں سکھا سکتا ہوں / پیشکش",
    iWantToLearn: "میں سیکھنا چاہتا ہوں",
    noSkillsYet: "ابھی تک کوئی مہارت شامل نہیں کی گئی۔",
    addNewSkill: "نئی مہارت شامل کریں",
    skillName: "مہارت کا نام",
    skillType: "قسم",
    canTeachOption: "میں یہ سکھا سکتا ہوں",
    wantLearnOption: "میں یہ سیکھنا چاہتا ہوں",
    addSkillButton: "مہارت شامل کریں",
    cameraOff: "کیمرہ بند",
    calling: "کال کی جا رہی ہے",
    displayName: "ڈسپلے نام",
    location: "مقام",
    bio: "تعارف",
    sessionWith: "نشست ساتھ",
    yesterday: "کل",
    mins: "منٹ",
    createAccount: "اکاؤنٹ بنائیں",
    signInAction: "سائن ان",
    createNewAccount: "نیا اکاؤنٹ بنائیں",
    signInExisting: "موجودہ اکاؤنٹ میں سائن ان کریں",
    backToHome: "ہوم پر واپس",
    demoMode: "ڈیمو موڈ۔"
  },
  es: {
    welcome: "Bienvenido de nuevo",
    home: "Inicio",
    matches: "Coincidencias",
    call: "Llamar",
    profile: "Perfil",
    logout: "Cerrar sesión",
    signIn: "Iniciar sesión",
    getStarted: "Empieza gratis",
    heroTitle: "Domina nuevas habilidades a través de la conexión humana real.",
    heroSub: "Intercambia tu experiencia por conocimiento. Enseña lo que sabes, aprende lo que no.",
    email: "Correo electrónico",
    phone: "Número de teléfono",
    password: "Contraseña",
    continueGoogle: "Continuar con Google",
    continueFacebook: "Continuar con Facebook",
    or: "O continuar con",
    pendingRequests: "Tienes 3 solicitudes pendientes.",
    hoursExchanged: "Horas intercambiadas",
    avgRating: "Calificación media",
    newSkills: "Nuevas habilidades",
    aiAssistant: "Asistente de aprendizaje IA",
    generateRoadmap: "Generar hoja de ruta",
    recentActivity: "Actividad reciente",
    quickActions: "Acciones rápidas",
    scheduleCall: "Programar llamada",
    updateSkills: "Actualizar habilidades",
    recommendedMatches: "Coincidencias recomendadas",
    searchPlaceholder: "Buscar por nombre o habilidad...",
    callNow: "Llamar ahora",
    offers: "Ofrece",
    wants: "Busca",
    editProfile: "Editar perfil",
    saveChanges: "Guardar cambios",
    cancel: "Cancelar",
    suggestedPath: "Camino sugerido para",
    clear: "Limpiar",
    noMatches: "No se encontraron usuarios que coincidan con tus criterios.",
    aiSuggestion: "Sugerencia de IA",
    skillsExpertise: "Habilidades y experiencia",
    iCanTeach: "Puedo enseñar / Ofrecer",
    iWantToLearn: "Quiero aprender",
    noSkillsYet: "Aún no se han añadido habilidades.",
    addNewSkill: "Añadir nueva habilidad",
    skillName: "Nombre de la habilidad",
    skillType: "Tipo",
    canTeachOption: "Puedo enseñar esto",
    wantLearnOption: "Quiero aprender esto",
    addSkillButton: "Añadir habilidad",
    cameraOff: "Cámara apagada",
    calling: "Llamando",
    displayName: "Nombre para mostrar",
    location: "Ubicación",
    bio: "Biografía",
    sessionWith: "Sesión con",
    yesterday: "Ayer",
    mins: "minutos",
    createAccount: "Crear cuenta",
    signInAction: "Iniciar sesión",
    createNewAccount: "crear una cuenta nueva",
    signInExisting: "iniciar sesión en cuenta existente",
    backToHome: "Volver al inicio",
    demoMode: "Modo de demostración."
  },
  fr: {
    welcome: "Bon retour",
    home: "Accueil",
    matches: "Matchs",
    call: "Appel",
    profile: "Profil",
    logout: "Déconnexion",
    signIn: "Se connecter",
    getStarted: "Commencer gratuitement",
    heroTitle: "Maîtrisez de nouvelles compétences grâce à la connexion humaine.",
    heroSub: "Échangez votre expertise contre des connaissances. Enseignez ce que vous savez, apprenez le reste.",
    email: "Adresse e-mail",
    phone: "Numéro de téléphone",
    password: "Mot de passe",
    continueGoogle: "Continuer avec Google",
    continueFacebook: "Continuer avec Facebook",
    or: "Ou continuer avec",
    pendingRequests: "Vous avez 3 demandes en attente.",
    hoursExchanged: "Heures échangées",
    avgRating: "Note moyenne",
    newSkills: "Nouvelles compétences",
    aiAssistant: "Assistant d'apprentissage IA",
    generateRoadmap: "Générer feuille de route",
    recentActivity: "Activité récente",
    quickActions: "Actions rapides",
    scheduleCall: "Planifier un appel",
    updateSkills: "Mettre à jour compétences",
    recommendedMatches: "Matchs recommandés",
    searchPlaceholder: "Chercher par nom ou compétence...",
    callNow: "Appeler",
    offers: "Offre",
    wants: "Recherche",
    editProfile: "Modifier profil",
    saveChanges: "Sauvegarder",
    cancel: "Annuler",
    suggestedPath: "Chemin suggéré pour",
    clear: "Effacer",
    noMatches: "Aucun utilisateur trouvé correspondant à vos critères.",
    aiSuggestion: "Suggestion IA",
    skillsExpertise: "Compétences et expertise",
    iCanTeach: "Je peux enseigner / Offrir",
    iWantToLearn: "Je veux apprendre",
    noSkillsYet: "Aucune compétence ajoutée pour le moment.",
    addNewSkill: "Ajouter une compétence",
    skillName: "Nom de la compétence",
    skillType: "Type",
    canTeachOption: "Je peux enseigner ceci",
    wantLearnOption: "Je veux apprendre ceci",
    addSkillButton: "Ajouter compétence",
    cameraOff: "Caméra éteinte",
    calling: "Appel en cours",
    displayName: "Nom d'affichage",
    location: "Lieu",
    bio: "Biographie",
    sessionWith: "Séance avec",
    yesterday: "Hier",
    mins: "min",
    createAccount: "Créer un compte",
    signInAction: "Se connecter",
    createNewAccount: "créer un nouveau compte",
    signInExisting: "se connecter à un compte existant",
    backToHome: "Retour à l'accueil",
    demoMode: "Mode démo."
  },
  zh: {
    welcome: "欢迎回来",
    home: "首页",
    matches: "匹配",
    call: "通话",
    profile: "个人资料",
    logout: "登出",
    signIn: "登录",
    getStarted: "免费开始",
    heroTitle: "通过真实的人际交往掌握新技能。",
    heroSub: "用你的专长交换知识。教你所知，学你所缺。",
    email: "电子邮箱",
    phone: "电话号码",
    password: "密码",
    continueGoogle: "通过 Google 继续",
    continueFacebook: "通过 Facebook 继续",
    or: "或通过以下方式继续",
    pendingRequests: "您有 3 个待处理的请求。",
    hoursExchanged: "交换时长",
    avgRating: "平均评分",
    newSkills: "新技能",
    aiAssistant: "AI 学习助手",
    generateRoadmap: "生成学习路线",
    recentActivity: "近期活动",
    quickActions: "快速操作",
    scheduleCall: "预约通话",
    updateSkills: "更新技能",
    recommendedMatches: "推荐匹配",
    searchPlaceholder: "按姓名或技能搜索...",
    callNow: "立即通话",
    offers: "提供",
    wants: "想要",
    editProfile: "编辑资料",
    saveChanges: "保存更改",
    cancel: "取消",
    suggestedPath: "建议的学习路径：",
    clear: "清除",
    noMatches: "未找到符合您条件的用户。",
    aiSuggestion: "AI 建议",
    skillsExpertise: "技能与专长",
    iCanTeach: "我可以教 / 提供",
    iWantToLearn: "我想学",
    noSkillsYet: "暂未添加技能。",
    addNewSkill: "添加新技能",
    skillName: "技能名称",
    skillType: "类型",
    canTeachOption: "我可以教这个",
    wantLearnOption: "我想学这个",
    addSkillButton: "添加技能",
    cameraOff: "摄像头已关闭",
    calling: "呼叫中",
    displayName: "显示名称",
    location: "位置",
    bio: "简介",
    sessionWith: "与...的会话",
    yesterday: "昨天",
    mins: "分钟",
    createAccount: "创建账户",
    signInAction: "登录",
    createNewAccount: "创建新账户",
    signInExisting: "登录现有账户",
    backToHome: "返回首页",
    demoMode: "演示模式。"
  },
  ar: {
    welcome: "مرحباً بعودتك",
    home: "الرئيسية",
    matches: "المطابقات",
    call: "اتصال",
    profile: "الملف الشخصي",
    logout: "تسجيل خروج",
    signIn: "تسجيل الدخول",
    getStarted: "ابدأ مجانًا",
    heroTitle: "أتقن مهارات جديدة من خلال التواصل البشري الحقيقي.",
    heroSub: "تبادل خبراتك بالمعرفة. علم ما تعرفه، وتعلم ما لا تعرفه.",
    email: "البريد الإلكتروني",
    phone: "رقم الهاتف",
    password: "كلمة المرور",
    continueGoogle: "المتابعة باستخدام Google",
    continueFacebook: "المتابعة باستخدام Facebook",
    or: "أو المتابعة باستخدام",
    pendingRequests: "لديك 3 طلبات مطابقة معلقة.",
    hoursExchanged: "ساعات التبادل",
    avgRating: "متوسط التقييم",
    newSkills: "مهارات جديدة",
    aiAssistant: "مساعد التعلم بالذكاء الاصطناعي",
    generateRoadmap: "إنشاء خارطة طريق",
    recentActivity: "النشاط الأخير",
    quickActions: "إجراءات سريعة",
    scheduleCall: "جدولة مكالمة",
    updateSkills: "تحديث المهارات",
    recommendedMatches: "المطابقات الموصى بها",
    searchPlaceholder: "البحث بالاسم أو المهارة...",
    callNow: "اتصل الآن",
    offers: "يعرض",
    wants: "يريد",
    editProfile: "تعديل الملف الشخصي",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    suggestedPath: "المسار المقترح لـ",
    clear: "مسح",
    noMatches: "لم يتم العثور على مستخدمين مطابقين لمعاييرك.",
    aiSuggestion: "اقتراح الذكاء الاصطناعي",
    skillsExpertise: "المهارات والخبرات",
    iCanTeach: "أستطيع تعليم / تقديم",
    iWantToLearn: "أريد أن أتعلم",
    noSkillsYet: "لم تتم إضافة مهارات بعد.",
    addNewSkill: "إضافة مهارة جديدة",
    skillName: "اسم المهارة",
    skillType: "النوع",
    canTeachOption: "أستطيع تعليم هذا",
    wantLearnOption: "أريد تعلم هذا",
    addSkillButton: "إضافة مهارة",
    cameraOff: "الكاميرا مغلقة",
    calling: "جاري الاتصال",
    displayName: "الاسم المعروض",
    location: "الموقع",
    bio: "السيرة الذاتية",
    sessionWith: "جلسة مع",
    yesterday: "أمس",
    mins: "دقيقة",
    createAccount: "إنشاء حساب",
    signInAction: "تسجيل الدخول",
    createNewAccount: "إنشاء حساب جديد",
    signInExisting: "تسجيل الدخول لحساب موجود",
    backToHome: "العودة للصفحة الرئيسية",
    demoMode: "الوضع التجريبي."
  },
  de: {
    welcome: "Willkommen zurück",
    home: "Startseite",
    matches: "Matches",
    call: "Anruf",
    profile: "Profil",
    logout: "Abmelden",
    signIn: "Anmelden",
    getStarted: "Kostenlos starten",
    heroTitle: "Meistern Sie neue Fähigkeiten durch echte menschliche Verbindungen.",
    heroSub: "Tauschen Sie Ihr Fachwissen gegen Wissen. Lehren Sie, was Sie wissen, lernen Sie, was Sie nicht wissen.",
    email: "E-Mail-Adresse",
    phone: "Telefonnummer",
    password: "Passwort",
    continueGoogle: "Weiter mit Google",
    continueFacebook: "Weiter mit Facebook",
    or: "Oder weiter mit",
    pendingRequests: "Sie haben 3 ausstehende Match-Anfragen.",
    hoursExchanged: "Getauschte Stunden",
    avgRating: "Durchschnittsbewertung",
    newSkills: "Neue Fähigkeiten",
    aiAssistant: "KI-Lernassistent",
    generateRoadmap: "Roadmap erstellen",
    recentActivity: "Letzte Aktivitäten",
    quickActions: "Schnellaktionen",
    scheduleCall: "Anruf planen",
    updateSkills: "Fähigkeiten aktualisieren",
    recommendedMatches: "Empfohlene Matches",
    searchPlaceholder: "Nach Name oder Fähigkeit suchen...",
    callNow: "Jetzt anrufen",
    offers: "Bietet",
    wants: "Sucht",
    editProfile: "Profil bearbeiten",
    saveChanges: "Änderungen speichern",
    cancel: "Abbrechen",
    suggestedPath: "Vorgeschlagener Pfad für",
    clear: "Löschen",
    noMatches: "Keine Benutzer gefunden, die Ihren Kriterien entsprechen.",
    aiSuggestion: "KI-Vorschlag",
    skillsExpertise: "Fähigkeiten & Expertise",
    iCanTeach: "Ich kann lehren / Bieten",
    iWantToLearn: "Ich möchte lernen",
    noSkillsYet: "Noch keine Fähigkeiten hinzugefügt.",
    addNewSkill: "Neue Fähigkeit hinzufügen",
    skillName: "Fähigkeitsname",
    skillType: "Typ",
    canTeachOption: "Ich kann das lehren",
    wantLearnOption: "Ich möchte das lernen",
    addSkillButton: "Fähigkeit hinzufügen",
    cameraOff: "Kamera aus",
    calling: "Rufe an",
    displayName: "Anzeigename",
    location: "Standort",
    bio: "Biografie",
    sessionWith: "Sitzung mit",
    yesterday: "Gestern",
    mins: "Min.",
    createAccount: "Konto erstellen",
    signInAction: "Anmelden",
    createNewAccount: "neues Konto erstellen",
    signInExisting: "in bestehendes Konto einloggen",
    backToHome: "Zurück zur Startseite",
    demoMode: "Demo-Modus."
  },
  ru: {
    welcome: "С возвращением",
    home: "Главная",
    matches: "Совпадения",
    call: "Звонок",
    profile: "Профиль",
    logout: "Выйти",
    signIn: "Войти",
    getStarted: "Начать бесплатно",
    heroTitle: "Осваивайте новые навыки через живое общение.",
    heroSub: "Обменивайте свой опыт на знания. Учите тому, что знаете, учитесь тому, чего не знаете.",
    email: "Электронная почта",
    phone: "Номер телефона",
    password: "Пароль",
    continueGoogle: "Продолжить с Google",
    continueFacebook: "Продолжить с Facebook",
    or: "Или продолжить с",
    pendingRequests: "У вас 3 ожидающих запроса.",
    hoursExchanged: "Часов обмена",
    avgRating: "Средний рейтинг",
    newSkills: "Новые навыки",
    aiAssistant: "ИИ-ассистент обучения",
    generateRoadmap: "Создать план",
    recentActivity: "Недавняя активность",
    quickActions: "Быстрые действия",
    scheduleCall: "Запланировать звонок",
    updateSkills: "Обновить навыки",
    recommendedMatches: "Рекомендуемые",
    searchPlaceholder: "Поиск по имени или навыку...",
    callNow: "Позвонить",
    offers: "Предлагает",
    wants: "Хочет",
    editProfile: "Редактировать профиль",
    saveChanges: "Сохранить изменения",
    cancel: "Отмена",
    suggestedPath: "Предлагаемый путь для",
    clear: "Очистить",
    noMatches: "Пользователи по вашим критериям не найдены.",
    aiSuggestion: "Предложение ИИ",
    skillsExpertise: "Навыки и опыт",
    iCanTeach: "Могу научить / Предлагаю",
    iWantToLearn: "Хочу научиться",
    noSkillsYet: "Навыки пока не добавлены.",
    addNewSkill: "Добавить новый навык",
    skillName: "Название навыка",
    skillType: "Тип",
    canTeachOption: "Могу научить этому",
    wantLearnOption: "Хочу научиться этому",
    addSkillButton: "Добавить навык",
    cameraOff: "Камера выкл",
    calling: "Вызов",
    displayName: "Отображаемое имя",
    location: "Местоположение",
    bio: "О себе",
    sessionWith: "Сессия с",
    yesterday: "Вчера",
    mins: "мин",
    createAccount: "Создать аккаунт",
    signInAction: "Войти",
    createNewAccount: "создать новый аккаунт",
    signInExisting: "войти в существующий",
    backToHome: "На главную",
    demoMode: "Демо-режим."
  },
  pt: {
    welcome: "Bem-vindo de volta",
    home: "Início",
    matches: "Pares",
    call: "Chamar",
    profile: "Perfil",
    logout: "Sair",
    signIn: "Entrar",
    getStarted: "Comece Grátis",
    heroTitle: "Domine novas habilidades através de conexão humana real.",
    heroSub: "Troque sua experiência por conhecimento. Ensine o que sabe, aprenda o que não sabe.",
    email: "Endereço de e-mail",
    phone: "Número de telefone",
    password: "Senha",
    continueGoogle: "Continuar com Google",
    continueFacebook: "Continuar com Facebook",
    or: "Ou continuar com",
    pendingRequests: "Você tem 3 solicitações pendentes.",
    hoursExchanged: "Horas Trocadas",
    avgRating: "Avaliação Média",
    newSkills: "Novas Habilidades",
    aiAssistant: "Assistente de Aprendizagem IA",
    generateRoadmap: "Gerar Roteiro",
    recentActivity: "Atividade Recente",
    quickActions: "Ações Rápidas",
    scheduleCall: "Agendar Chamada",
    updateSkills: "Atualizar Habilidades",
    recommendedMatches: "Pares Recomendados",
    searchPlaceholder: "Buscar por nome ou habilidade...",
    callNow: "Ligar Agora",
    offers: "Oferece",
    wants: "Procura",
    editProfile: "Editar Perfil",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    suggestedPath: "Caminho sugerido para",
    clear: "Limpar",
    noMatches: "Nenhum usuário encontrado com seus critérios.",
    aiSuggestion: "Sugestão da IA",
    skillsExpertise: "Habilidades e Especialização",
    iCanTeach: "Posso Ensinar / Ofereço",
    iWantToLearn: "Quero Aprender",
    noSkillsYet: "Nenhuma habilidade adicionada ainda.",
    addNewSkill: "Adicionar Nova Habilidade",
    skillName: "Nome da Habilidade",
    skillType: "Tipo",
    canTeachOption: "Posso ensinar isso",
    wantLearnOption: "Quero aprender isso",
    addSkillButton: "Adicionar Habilidade",
    cameraOff: "Câmera Desligada",
    calling: "Chamando",
    displayName: "Nome de Exibição",
    location: "Localização",
    bio: "Biografia",
    sessionWith: "Sessão com",
    yesterday: "Ontem",
    mins: "min",
    createAccount: "Criar Conta",
    signInAction: "Entrar",
    createNewAccount: "criar uma nova conta",
    signInExisting: "entrar em conta existente",
    backToHome: "Voltar ao Início",
    demoMode: "Modo de Demonstração."
  },
  ja: {
    welcome: "お帰りなさい",
    home: "ホーム",
    matches: "マッチ",
    call: "通話",
    profile: "プロフィール",
    logout: "ログアウト",
    signIn: "サインイン",
    getStarted: "無料で始める",
    heroTitle: "リアルな人間関係を通じて新しいスキルを習得しましょう。",
    heroSub: "あなたの専門知識を知識と交換しましょう。知っていることを教え、知らないことを学びましょう。",
    email: "メールアドレス",
    phone: "電話番号",
    password: "パスワード",
    continueGoogle: "Googleで続ける",
    continueFacebook: "Facebookで続ける",
    or: "または次で続ける",
    pendingRequests: "3件の保留中のリクエストがあります。",
    hoursExchanged: "交換時間",
    avgRating: "平均評価",
    newSkills: "新しいスキル",
    aiAssistant: "AI学習アシスタント",
    generateRoadmap: "ロードマップを作成",
    recentActivity: "最近のアクティビティ",
    quickActions: "クイックアクション",
    scheduleCall: "通話を予約",
    updateSkills: "スキルを更新",
    recommendedMatches: "おすすめのマッチ",
    searchPlaceholder: "名前またはスキルで検索...",
    callNow: "今すぐ通話",
    offers: "提供",
    wants: "希望",
    editProfile: "プロフィールを編集",
    saveChanges: "変更を保存",
    cancel: "キャンセル",
    suggestedPath: "提案されたパス：",
    clear: "クリア",
    noMatches: "条件に一致するユーザーが見つかりませんでした。",
    aiSuggestion: "AIの提案",
    skillsExpertise: "スキルと専門知識",
    iCanTeach: "教えられる / 提供",
    iWantToLearn: "学びたい",
    noSkillsYet: "スキルはまだ追加されていません。",
    addNewSkill: "新しいスキルを追加",
    skillName: "スキル名",
    skillType: "タイプ",
    canTeachOption: "これを教えられます",
    wantLearnOption: "これを学びたいです",
    addSkillButton: "スキルを追加",
    cameraOff: "カメラオフ",
    calling: "発信中",
    displayName: "表示名",
    location: "場所",
    bio: "自己紹介",
    sessionWith: "セッション相手：",
    yesterday: "昨日",
    mins: "分",
    createAccount: "アカウント作成",
    signInAction: "サインイン",
    createNewAccount: "新しいアカウントを作成",
    signInExisting: "既存のアカウントにサインイン",
    backToHome: "ホームに戻る",
    demoMode: "デモモード。"
  },
  ko: {
    welcome: "환영합니다",
    home: "홈",
    matches: "매칭",
    call: "통화",
    profile: "프로필",
    logout: "로그아웃",
    signIn: "로그인",
    getStarted: "무료로 시작하기",
    heroTitle: "진정한 인간 관계를 통해 새로운 기술을 마스터하세요.",
    heroSub: "당신의 전문 지식을 지식과 교환하세요. 아는 것을 가르치고, 모르는 것을 배우세요.",
    email: "이메일 주소",
    phone: "전화번호",
    password: "비밀번호",
    continueGoogle: "Google로 계속",
    continueFacebook: "Facebook으로 계속",
    or: "또는 다음으로 계속",
    pendingRequests: "3개의 대기 중인 요청이 있습니다.",
    hoursExchanged: "교환된 시간",
    avgRating: "평균 평점",
    newSkills: "새로운 기술",
    aiAssistant: "AI 학습 도우미",
    generateRoadmap: "로드맵 생성",
    recentActivity: "최근 활동",
    quickActions: "빠른 작업",
    scheduleCall: "통화 예약",
    updateSkills: "기술 업데이트",
    recommendedMatches: "추천 매칭",
    searchPlaceholder: "이름 또는 기술로 검색...",
    callNow: "지금 통화",
    offers: "제공",
    wants: "원함",
    editProfile: "프로필 수정",
    saveChanges: "변경 사항 저장",
    cancel: "취소",
    suggestedPath: "제안된 경로:",
    clear: "지우기",
    noMatches: "조건에 맞는 사용자를 찾을 수 없습니다.",
    aiSuggestion: "AI 제안",
    skillsExpertise: "기술 및 전문성",
    iCanTeach: "가르칠 수 있음 / 제공",
    iWantToLearn: "배우고 싶음",
    noSkillsYet: "아직 추가된 기술이 없습니다.",
    addNewSkill: "새 기술 추가",
    skillName: "기술 이름",
    skillType: "유형",
    canTeachOption: "이것을 가르칠 수 있습니다",
    wantLearnOption: "이것을 배우고 싶습니다",
    addSkillButton: "기술 추가",
    cameraOff: "카메라 끄기",
    calling: "연결 중",
    displayName: "표시 이름",
    location: "위치",
    bio: "소개",
    sessionWith: "세션 상대:",
    yesterday: "어제",
    mins: "분",
    createAccount: "계정 생성",
    signInAction: "로그인",
    createNewAccount: "새 계정 만들기",
    signInExisting: "기존 계정으로 로그인",
    backToHome: "홈으로 돌아가기",
    demoMode: "데모 모드."
  },
  it: {
    welcome: "Bentornato",
    home: "Home",
    matches: "Abbinamenti",
    call: "Chiama",
    profile: "Profilo",
    logout: "Esci",
    signIn: "Accedi",
    getStarted: "Inizia Gratis",
    heroTitle: "Padroneggia nuove abilità attraverso connessioni umane reali.",
    heroSub: "Scambia la tua esperienza per conoscenza. Insegna ciò che sai, impara ciò che non sai.",
    email: "Indirizzo email",
    phone: "Numero di telefono",
    password: "Password",
    continueGoogle: "Continua con Google",
    continueFacebook: "Continua con Facebook",
    or: "O continua con",
    pendingRequests: "Hai 3 richieste in sospeso.",
    hoursExchanged: "Ore Scambiate",
    avgRating: "Voto Medio",
    newSkills: "Nuove Abilità",
    aiAssistant: "Assistente Apprendimento IA",
    generateRoadmap: "Genera Percorso",
    recentActivity: "Attività Recente",
    quickActions: "Azioni Rapide",
    scheduleCall: "Pianifica Chiamata",
    updateSkills: "Aggiorna Abilità",
    recommendedMatches: "Abbinamenti Consigliati",
    searchPlaceholder: "Cerca per nome o abilità...",
    callNow: "Chiama Ora",
    offers: "Offre",
    wants: "Cerca",
    editProfile: "Modifica Profilo",
    saveChanges: "Salva Modifiche",
    cancel: "Annulla",
    suggestedPath: "Percorso suggerito per",
    clear: "Pulisci",
    noMatches: "Nessun utente trovato con i tuoi criteri.",
    aiSuggestion: "Suggerimento IA",
    skillsExpertise: "Abilità ed Esperienza",
    iCanTeach: "Posso Insegnare / Offro",
    iWantToLearn: "Voglio Imparare",
    noSkillsYet: "Nessuna abilità aggiunta.",
    addNewSkill: "Aggiungi Nuova Abilità",
    skillName: "Nome Abilità",
    skillType: "Tipo",
    canTeachOption: "Posso insegnare questo",
    wantLearnOption: "Voglio imparare questo",
    addSkillButton: "Aggiungi Abilità",
    cameraOff: "Fotocamera Spenta",
    calling: "Chiamata in corso",
    displayName: "Nome Visualizzato",
    location: "Posizione",
    bio: "Biografia",
    sessionWith: "Sessione con",
    yesterday: "Ieri",
    mins: "min",
    createAccount: "Crea Account",
    signInAction: "Accedi",
    createNewAccount: "crea un nuovo account",
    signInExisting: "accedi a un account esistente",
    backToHome: "Torna alla Home",
    demoMode: "Modalità Demo."
  },
  tr: {
    welcome: "Tekrar hoş geldiniz",
    home: "Ana Sayfa",
    matches: "Eşleşmeler",
    call: "Ara",
    profile: "Profil",
    logout: "Çıkış Yap",
    signIn: "Giriş Yap",
    getStarted: "Ücretsiz Başla",
    heroTitle: "Gerçek insan bağlantılarıyla yeni beceriler edinin.",
    heroSub: "Uzmanlığınızı bilgiyle takas edin. Bildiğinizi öğretin, bilmediğinizi öğrenin.",
    email: "E-posta adresi",
    phone: "Telefon Numarası",
    password: "Şifre",
    continueGoogle: "Google ile Devam Et",
    continueFacebook: "Facebook ile Devam Et",
    or: "Veya şununla devam et",
    pendingRequests: "3 bekleyen isteğiniz var.",
    hoursExchanged: "Değişilen Saatler",
    avgRating: "Ortalama Puan",
    newSkills: "Yeni Beceriler",
    aiAssistant: "YZ Öğrenme Asistanı",
    generateRoadmap: "Yol Haritası Oluştur",
    recentActivity: "Son Etkinlikler",
    quickActions: "Hızlı İşlemler",
    scheduleCall: "Arama Planla",
    updateSkills: "Becerileri Güncelle",
    recommendedMatches: "Önerilen Eşleşmeler",
    searchPlaceholder: "İsim veya beceri ile ara...",
    callNow: "Şimdi Ara",
    offers: "Sunuyor",
    wants: "İstiyor",
    editProfile: "Profili Düzenle",
    saveChanges: "Değişiklikleri Kaydet",
    cancel: "İptal",
    suggestedPath: "Önerilen yol:",
    clear: "Temizle",
    noMatches: "Kriterlerinize uyan kullanıcı bulunamadı.",
    aiSuggestion: "YZ Önerisi",
    skillsExpertise: "Beceriler ve Uzmanlık",
    iCanTeach: "Öğretebilirim / Sunuyorum",
    iWantToLearn: "Öğrenmek İstiyorum",
    noSkillsYet: "Henüz beceri eklenmedi.",
    addNewSkill: "Yeni Beceri Ekle",
    skillName: "Beceri Adı",
    skillType: "Tür",
    canTeachOption: "Bunu öğretebilirim",
    wantLearnOption: "Bunu öğrenmek istiyorum",
    addSkillButton: "Beceri Ekle",
    cameraOff: "Kamera Kapalı",
    calling: "Aranıyor",
    displayName: "Görünen Ad",
    location: "Konum",
    bio: "Biyografi",
    sessionWith: "İle oturum",
    yesterday: "Dün",
    mins: "dk",
    createAccount: "Hesap Oluştur",
    signInAction: "Giriş Yap",
    createNewAccount: "yeni hesap oluştur",
    signInExisting: "mevcut hesaba giriş yap",
    backToHome: "Ana Sayfaya Dön",
    demoMode: "Demo Modu."
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const dir = (language === 'ar' || language === 'ur') ? 'rtl' : 'ltr';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir }}>
      <div dir={dir} className={language === 'ur' ? 'font-urdu' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LANGUAGE_NAMES: Record<Language, string> = {
  en: "English",
  hi: "हिंदी (Hindi)",
  ur: "اردو (Urdu)",
  es: "Español",
  fr: "Français",
  zh: "中文 (Chinese)",
  ar: "العربية (Arabic)",
  de: "Deutsch (German)",
  ru: "Русский (Russian)",
  pt: "Português (Portuguese)",
  ja: "日本語 (Japanese)",
  ko: "한국어 (Korean)",
  it: "Italiano (Italian)",
  tr: "Türkçe (Turkish)"
};